# Generated by Django 4.1 on 2025-01-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='出版社名称')),
            ],
            options={
                'verbose_name': '出版社类',
                'verbose_name_plural': '出版社',
                'db_table': 'author_in_otm',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=11, verbose_name='书名')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otm.publisher')),
            ],
            options={
                'verbose_name': '图书类',
                'verbose_name_plural': '图书',
                'db_table': 'book_in_otm',
            },
        ),
    ]
