# Generated by Django 4.1 on 2025-01-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='作者',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
