# Generated by Django 4.1 on 2025-01-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_author_table_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
