# Generated by Django 4.1 on 2025-01-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_remove_book_into_book_market_price_book_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
