# Generated by Django 4.1 on 2025-01-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者类', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书类', 'verbose_name_plural': '图书'},
        ),
    ]
