# Generated by Django 4.1 on 2025-01-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者类', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': '妻子类', 'verbose_name_plural': '妻子'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author_in_oto',
        ),
        migrations.AlterModelTable(
            name='wife',
            table='wife_in_oto',
        ),
    ]
