# Generated by Django 4.1 on 2025-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
