# Generated by Django 4.1 on 2025-01-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '作者类',
                'verbose_name_plural': '作者',
                'db_table': 'author_in_mtm',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=11, verbose_name='书名')),
                ('books', models.ManyToManyField(to='mtm.author')),
            ],
            options={
                'verbose_name': '图书类',
                'verbose_name_plural': '图书',
                'db_table': 'book_in_mtm',
            },
        ),
    ]
